### PR TITLE
Add support for tileoffset of tilesets

### PR DESCRIPTION
**Pull request by Anka4**

### CODE REVIEW

**Comment by RandyGaul** [comment]
Is there any reason the point is allocated? Instead, could the point simply be more like this:

```cpp
	int tilecount;                       // The number of tiles in this tileset.
	cute_tiled_string_t tiledversion;    // The Tiled version used to save the tileset.
	int tileheight;                      // Maximum height of tiles in this set.
	int tileoffset_x;      // Pixel offset to align tiles to the grid.
	int tileoffset_y;      // Pixel offset to align tiles to the grid.
	cute_tiled_tile_descriptor_t* tiles; // Linked list of tile descriptors. Can be NULL.
	int tilewidth;                       // Maximum width of tiles in this set.
	int transparentcolor;                // Hex-formatted color (#RRGGBB or #AARRGGBB) (optional).
```

**Comment by Anka4** [comment]
I did it like this for consistency with the parsed JSON structure:

`{
    ...
    "tileoffset": {
        "x":12,
        "y":0
     },
}`

the code can indeed be simplified if you don't want it

**Comment by RandyGaul** [comment]
Oh I see, you were trying to represent as is in JSON. Makes sense. Please do adjust your PR a little bit. The function you wrote for parsing the x/y point is a great function, it just doesn't need to allocate. The only change would be tileoffset_x and tileoffset_y as integers directly in the tile descriptor struct.

Thanks so much for making a contribution! Pull requests like these are very valuable for cute_tiled :)

**Comment by RandyGaul** [comment]
Looks great, thanks for adding this!

**Comment by RandyGaul** [comment]
One piece was missing -- these macros are used to pop up the callstack and report errors. Kind of like an exception. Added this to your point reading function.

https://github.com/RandyGaul/cute_headers/commit/f98d22c97d6a09315afcb05c194bc3fd00d89814

**Pull request merged**
