### PR TITLE
Fix wrong unfilter values for first scanline (cute_png)

### PR DESCRIPTION
**Pull request by dkorpel**
cute_png currently messes up on PNG's with a filter for the first scanline that accesses the previous scanline. It is specified that when unfiltering the first scanline, the previous line is supposed to be all zero. cute_png however treats the previous scanline as the current scanline, yielding incorrect results.
```C
uint8_t *prev = raw;
```

This PR fixes it by unrolling the first iteration out of the loop, which is a bit more code, but it avoids extra branching or allocation of an array of zeros.

### CODE REVIEW

**Comment by RandyGaul** [comment]
Interesting... Are you sure this code is correct? You've modified some original Mitton code that I haven't actually taken the time to understand. Your other PRs were solid, so I'm assuming this one is as well. If anyone has problems, we can try reverting this fix in the future, but for now I'll assume your fix is correct.

**Comment by RandyGaul** [comment]
It would be really helpful if you code post an example image where the error, before and after the fix. This way it can be saved here for future reference and testing @dkorpel

**Comment by RandyGaul** [comment]
I also spotted some messed up whitespace, could you please add another commit to this PR to fix that up? :)

image

**Comment by dkorpel** [comment]
> Are you sure this code is correct? You've modified some original Mitton code that I haven't actually taken the time to understand

I don't know who Mitton is, but [stb_image](https://github.com/nothings/stb/blob/052dce117ed989848a950308bd99eef55525dfb1/stb_image.h#L4439) does something similar.

> It would be really helpful if you code post an example image where the error, before and after the fix (two images, one with the corrupt first scanline, and one without any flaws). This way it can be saved here for future reference and testing @dkorpel

I encountered this when loading letters from a font generated by [msdfgen](https://github.com/Chlumsky/msdfgen) (which uses LodePNG btw). Half the letters were corrupted, for example:
depalette
Was loaded in as:
depaletteOut

The image makes extensive use of filters, so the error in the first scanline cascades throughout the entire image. After this PR this image loads in correctly. I haven't tested all 4 first-line filters because I don't know how to generate PNG's with specific filter features, but I now see we can use images from [pngsuite](http://www.schaik.com/pngsuite/) for that.

**Comment by RandyGaul** [comment]
Thanks for posting up these images!

Mitton was the original author (Richard Mitton @ codersnotes.com)  of most of the inflate and png stuff in cute_png. I’ve changed a lot of it and people have helped fix quite a few bugs now, as time goes on, but the filters was the last part I never quite understood.

**Pull request merged**
