### PR TITLE
aseprite: Allow changing File IO functions

### PR DESCRIPTION
**Pull request by RobLoach**
Was looking to either change, or disable the file loading, so this is what I came up with. I'm not sure if this is the appropriate way of handling it. If you have other suggestions, I'm all ears!

### CODE REVIEW

**Comment by RandyGaul** [comment]
Actually looks fine to me, though I'm curious, was `cute_aseprite_load_from_memory` not enough for your use case?

**Comment by RobLoach** [comment]
`cute_aseprite_load_from_memory()` was perfectly fine for my use case. Mostly was trying to avoid stdio.h if not needed.

**Comment by RobLoach** [comment]
Thanks a lot, @RandyGaul. If you'd like me to apply a similar pattern to the other headers, let me know.

**Comment by RandyGaul** [comment]
@RobLoach Sure thing, if you're up for it! You did a good job here so I'm sure others PRs would be high quality too :)

**Pull request merged**
